fail_fast: false
exclude: |
  '.*\.decrypted~.*'
#    '.*.terraform/'
repos:
    #     - repo: https://github.com/adrienverge/yamllint
    #       rev: v1.30.0
    #       hooks:
    #         - args:
    #             - --config-file
    #             - .github/linters/.yamllint.yaml
    #           id: yamllint
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.5.0
      hooks:
        - id: check-merge-conflict
        - id: end-of-file-fixer
          exclude: |
            (?x)^(
              .*.terraform/.*|
              tmpl\/.*.sops\.ya?ml
              )$
        - id: mixed-line-ending
        - id: trailing-whitespace
          args:
            - --markdown-linebreak-ext=md
    - repo: https://github.com/Lucas-C/pre-commit-hooks
      rev: v1.5.5
      hooks:
        - id: remove-crlf
        - id: remove-tabs
    - repo: https://github.com/sirosen/texthooks
      rev: 0.6.6
      hooks:
        - id: fix-smartquotes
    - repo: https://github.com/djh00t/sops-pre-commit
      rev: v0.0.2f
      hooks:
        - id: kubernetes-secret
          # exclude: (k8s\/apps\/group-00\/kube-vip\/rbac.yaml|tmpl\/.*.sops\.ya?ml|knative\-operator\.ya?ml|tekton\-pipelines\.ya?ml)
        - id: aws-access-key-id
        - id: aws-secret-access-key
        - id: rsa-private-key
        - id: ssh-private-key
        - id: github-access-token
        - id: generic-api-key
        - id: gcp-api-key
        - id: jwt
        - id: slack-webhook-url
        - id: google-oauth-client-secret
###    - repo: local
###      hooks:
###        - id: kubernetes-secret
###          name: Check for unencrypted Kubernetes secrets
###          entry: python /Users/djh/work/src/github.com/djh00t/sops-pre-commit/hooks/forbid_secrets.py --hook-id kubernetes-secret
###          language: system
###          files: ((^|/)*.(ya?ml)$)
###        - id: aws-access-key-id
###          name: Check for AWS Access Key IDs
###          entry: python /Users/djh/work/src/github.com/djh00t/sops-pre-commit/hooks/forbid_secrets.py --hook-id aws-access-key-id
###          language: system
###          files: ((^|/)*.(ya?ml)$)
###        - id: aws-secret-access-key
###          name: Check for AWS Secret Access Keys
###          entry: python /Users/djh/work/src/github.com/djh00t/sops-pre-commit/hooks/forbid_secrets.py --hook-id aws-secret-access-key
###          language: system
###          files: ((^|/)*.(ya?ml)$)
###        - id: gcp-api-key
###          name: Check for GCP API Keys
###          entry: python /Users/djh/work/src/github.com/djh00t/sops-pre-commit/hooks/forbid_secrets.py --hook-id gcp-api-key
###          language: system
###          files: ((^|/)*.(ya?ml)$)
###        - id: generic-api-key
###          name: Check for Generic API Keys
###          entry: python /Users/djh/work/src/github.com/djh00t/sops-pre-commit/hooks/forbid_secrets.py --hook-id generic-api-key
###          language: system
###          files: ((^|/)*.(ya?ml)$)
###        - id: github-access-token
###          name: Check for GitHub Access Tokens
###          entry: python /Users/djh/work/src/github.com/djh00t/sops-pre-commit/hooks/forbid_secrets.py --hook-id github-access-token
###          language: system
###          files: ((^|/)*.(ya?ml)$)
###        - id: google-oauth-client-secret
###          name: Check for Google OAuth Client Secrets
###          entry: python /Users/djh/work/src/github.com/djh00t/sops-pre-commit/hooks/forbid_secrets.py --hook-id google-oauth-client-secret
###          language: system
###          files: ((^|/)*.(ya?ml)$)
###        - id: jwt
###          name: Check for JSON Web Tokens (JWT)
###          entry: python /Users/djh/work/src/github.com/djh00t/sops-pre-commit/hooks/forbid_secrets.py --hook-id jwt
###          language: system
###          files: ((^|/)*.(ya?ml)$)
###        - id: rsa-private-key
###          name: Check for RSA Private Keys
###          entry: python /Users/djh/work/src/github.com/djh00t/sops-pre-commit/hooks/forbid_secrets.py --hook-id rsa-private-key
###          language: system
###          files: ((^|/)*.(ya?ml)$)
###          exclude: (apps\/group-02\/clickhouse\/config\/configmap\.yaml|tmpl\/.*.sops\.ya?ml|knative\-operator\.ya?ml|tekton\-pipelines\.ya?ml)
###        - id: slack-webhook-url
###          name: Check for Slack Webhook URLs
###          entry: python /Users/djh/work/src/github.com/djh00t/sops-pre-commit/hooks/forbid_secrets.py --hook-id slack-webhook-url
###          language: system
###          files: ((^|/)*.(ya?ml)$)
###        - id: ssh-private-key
###          name: Check for SSH Private Keys
###          entry: python /Users/djh/work/src/github.com/djh00t/sops-pre-commit/hooks/forbid_secrets.py --hook-id ssh-private-key
###          language: system
###          files: ((^|/)*.(ya?ml)$)
    - repo: https://github.com/gruntwork-io/pre-commit
      rev: v0.1.23
      hooks:
        - id: terraform-fmt
        - id: terraform-validate
        - id: tflint
#        - id: shellcheck
#          args: ["-x -e SC1091"]
